/**
 * Standard Application Error Codes
 */
const ERROR_CODES = {
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  EXAM_NOT_AVAILABLE: 'EXAM_NOT_AVAILABLE',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_EXAM_TOKEN: 'INVALID_EXAM_TOKEN',
  EXAM_LOCKED: 'EXAM_LOCKED',
  SYNC_FAILED: 'SYNC_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'
};

module.exports = ERROR_CODES;
module.exports.ERROR_CODES = ERROR_CODES;
